// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EraserArgs = { width: number, };

export type PaintbrushArgs = { width: number, color: [number, number, number], };

export type Tool = { "tool": "Paintbrush" } & PaintbrushArgs | { "tool": "Eraser" } & EraserArgs;

export type UIMessage = { "type": "LoadFile" } | { "type": "SaveFile" } | { "type": "SetTool" } & Tool | { "type": "Undo" } | { "type": "Redo" };
